/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:787e7655-9efd-48dc-b6d3-198160c01822",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_mkntIHP1q",
    "aws_user_pools_web_client_id": "aqcnc9t5gs0af3kt91i0k9u6a",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7gcug2ezk5eajd6ldpah6nataq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mnawcvxbffajjdxodjq4fonfhe"
};


export default awsmobile;
